name: Bug Report
description: File a bug report.
labels: ["bug", "needs_review"]
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/ash-project/.github/blob/main/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: AI Policy
      description: By submitting this issue, you acknowledge our [AI Policy](https://github.com/ash-project/.github/blob/main/AI_POLICY.md). 
      options:
        - label: I agree that AI was not used, or that otherwise I agree to follow this project's AI Policy.
          required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: versions
    attributes:
      label: Versions
      description: |
        Please provide the relevant versions of Elixir, Erlang and any packages involved.
        Please check if upgrading to the latest version resolves the issue.
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      description: The operating system that this issue is happening on.
    validations:
      required: true
  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: |
        Include code samples, errors, and stacktraces if appropriate.
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: |
        In order to fix any bug, we will need to be able to reproduce it.
        Ideally, you will provide a minimal reproduction in a GitHub repository,
        or even better, make a PR with a failing test case.

        In liue of a failing test case, a reproduction should include:

        - All required setup instructions
        - Some automated step that is guaranteed to reproduce the same conditions,
          i.e an automated test or a function in a module that can be called from `iex`.
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: |
        A short description of what you expected to happen.
