name: Feature Proposal
description: Suggest an idea for this project.
labels: ["enhancement", "needs_review"]
body:
  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/ash-project/.github/blob/main/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: checkboxes
    id: ai-policy
    attributes:
      label: AI Policy
      description: By submitting this issue, you acknowledge our [AI Policy](https://github.com/ash-project/.github/blob/main/AI_POLICY.md). 
      options:
        - label: I agree to follow this project's AI Policy, or I agree that AI was not used while creating this issue.
          required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to propose a new feature!
  - type: textarea
    id: problem-description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: |
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution-description
    attributes:
      label: Describe the solution you'd like
      description: |
        A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives-considered
    attributes:
      label: Describe alternatives you've considered
      description: |
        A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here.
